In [1]:
import torch
import torch.nn as nn

In [2]:
X = torch.tensor(([2, 9], [1, 5], [3, 6]), dtype=torch.float)
y = torch.tensor(([92], [100], [89]), dtype=torch.float)
X_pred = torch.tensor(([4, 8]), dtype=torch.float)

In [3]:
print(X.size())
print(y.size())

torch.Size([3, 2])
torch.Size([3, 1])


In [4]:
X_max, _ = torch.max(X, 0)
X_pred_max, _ = torch.max(X_pred, 0)

X = torch.div(X, X_max)
X_pred = torch.div(X_pred, X_pred_max)
y = y / 100

In [5]:
class Neural_Network(nn.Module):
    def __init__(self, ):
        super(Neural_Network, self).__init__()
        # parameters
        # TODO: parameters can be parameterized instead of declaring them here
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 1
        
        # weights
        self.W1 = torch.randn(self.inputSize, self.hiddenSize) # 2 X 3 tensor
        self.W2 = torch.randn(self.hiddenSize, self.outputSize) # 3 X 1 tensor
        
    def forward(self, X):
        self.z = torch.matmul(X, self.W1) # 3 X 3 ".dot" does not broadcast in PyTorch
        self.z2 = self.sigmoid(self.z) # activation function
        self.z3 = torch.matmul(self.z2, self.W2)
        o = self.sigmoid(self.z3) # final activation function
        return o
        
    def sigmoid(self, s):
        return 1 / (1 + torch.exp(-s))
    
    def sigmoidPrime(self, s):
        # derivative of sigmoid
        return s * (1 - s)
    
    def backward(self, X, y, o):
        self.o_error = y - o # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # derivative of sig to error
        self.z2_error = torch.matmul(self.o_delta, torch.t(self.W2))
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.z2)
        self.W1 += torch.matmul(torch.t(X), self.z2_delta)
        self.W2 += torch.matmul(torch.t(self.z2), self.o_delta)
        
    def train(self, X, y):
        # forward + backward pass for training
        o = self.forward(X)
        self.backward(X, y, o)
        
    def saveWeights(self, model):
        # we will use the PyTorch internal storage functions
        torch.save(model, "NN")
        # you can reload model with all the weights and so forth with:
        # torch.load("NN")
        
    def predict(self):
        print ("Predicted data based on trained weights: ")
        print ("Input (scaled): \n" + str(X_pred))
        print ("Output: \n" + str(self.forward(X_pred)))

In [6]:
NN = Neural_Network()
for i in range(1000):  # trains the NN 1,000 times
    print ("#" + str(i) + " Loss: " + str(torch.mean((y - NN(X))**2).detach().item()))  # mean sum squared loss
    print(NN.W1)
    print(NN.W2)
    NN.train(X, y)
NN.saveWeights(NN)
NN.predict()

#0 Loss: 0.12358666211366653
tensor([[0.7045],
        [0.7989]])
tensor([[0.4869]])
#1 Loss: 0.10181859880685806
tensor([[0.7186],
        [0.8157]])
tensor([[0.6717]])
#2 Loss: 0.08469928056001663
tensor([[0.7354],
        [0.8358]])
tensor([[0.8346]])
#3 Loss: 0.0712064728140831
tensor([[0.7534],
        [0.8575]])
tensor([[0.9782]])
#4 Loss: 0.06051754951477051
tensor([[0.7714],
        [0.8795]])
tensor([[1.1053]])
#5 Loss: 0.05198885127902031
tensor([[0.7890],
        [0.9011]])
tensor([[1.2181]])
#6 Loss: 0.045125678181648254
tensor([[0.8059],
        [0.9220]])
tensor([[1.3187]])
#7 Loss: 0.03955162689089775
tensor([[0.8217],
        [0.9419]])
tensor([[1.4089]])
#8 Loss: 0.03498159348964691
tensor([[0.8366],
        [0.9608]])
tensor([[1.4901]])
#9 Loss: 0.03119945339858532
tensor([[0.8506],
        [0.9786]])
tensor([[1.5638]])
#10 Loss: 0.028040891513228416
tensor([[0.8635],
        [0.9954]])
tensor([[1.6308]])
#11 Loss: 0.02538020722568035
tensor([[0.8757],
        [1.0113

tensor([[2.9369]])
#110 Loss: 0.003687431337311864
tensor([[1.1317],
        [1.4450]])
tensor([[2.9401]])
#111 Loss: 0.003678738372400403
tensor([[1.1322],
        [1.4467]])
tensor([[2.9433]])
#112 Loss: 0.00367026892490685
tensor([[1.1328],
        [1.4484]])
tensor([[2.9464]])
#113 Loss: 0.0036620248574763536
tensor([[1.1333],
        [1.4501]])
tensor([[2.9495]])
#114 Loss: 0.0036539954598993063
tensor([[1.1338],
        [1.4517]])
tensor([[2.9525]])
#115 Loss: 0.003646167227998376
tensor([[1.1343],
        [1.4533]])
tensor([[2.9555]])
#116 Loss: 0.003638550406321883
tensor([[1.1348],
        [1.4549]])
tensor([[2.9584]])
#117 Loss: 0.0036311268340796232
tensor([[1.1353],
        [1.4565]])
tensor([[2.9613]])
#118 Loss: 0.003623881610110402
tensor([[1.1357],
        [1.4581]])
tensor([[2.9642]])
#119 Loss: 0.003616827540099621
tensor([[1.1362],
        [1.4597]])
tensor([[2.9670]])
#120 Loss: 0.0036099476274102926
tensor([[1.1367],
        [1.4613]])
tensor([[2.9698]])
#121 Loss:

        [1.6046]])
tensor([[3.1509]])
#252 Loss: 0.003301480785012245
tensor([[1.1575],
        [1.6054]])
tensor([[3.1515]])
#253 Loss: 0.0033007811289280653
tensor([[1.1575],
        [1.6062]])
tensor([[3.1521]])
#254 Loss: 0.0033000910189002752
tensor([[1.1575],
        [1.6070]])
tensor([[3.1527]])
#255 Loss: 0.003299406496807933
tensor([[1.1575],
        [1.6079]])
tensor([[3.1533]])
#256 Loss: 0.003298721509054303
tensor([[1.1575],
        [1.6087]])
tensor([[3.1539]])
#257 Loss: 0.003298049094155431
tensor([[1.1575],
        [1.6095]])
tensor([[3.1545]])
#258 Loss: 0.003297386923804879
tensor([[1.1575],
        [1.6103]])
tensor([[3.1551]])
#259 Loss: 0.0032967329025268555
tensor([[1.1575],
        [1.6112]])
tensor([[3.1556]])
#260 Loss: 0.003296074690297246
tensor([[1.1575],
        [1.6120]])
tensor([[3.1562]])
#261 Loss: 0.0032954325433820486
tensor([[1.1575],
        [1.6128]])
tensor([[3.1568]])
#262 Loss: 0.003294795984402299
tensor([[1.1575],
        [1.6136]])
tensor([[

#400 Loss: 0.0032392547000199556
tensor([[1.1492],
        [1.7119]])
tensor([[3.1948]])
#401 Loss: 0.0032389704138040543
tensor([[1.1491],
        [1.7125]])
tensor([[3.1949]])
#402 Loss: 0.003238685429096222
tensor([[1.1490],
        [1.7132]])
tensor([[3.1950]])
#403 Loss: 0.003238398814573884
tensor([[1.1489],
        [1.7138]])
tensor([[3.1951]])
#404 Loss: 0.003238111501559615
tensor([[1.1488],
        [1.7145]])
tensor([[3.1951]])
#405 Loss: 0.0032378218602389097
tensor([[1.1487],
        [1.7151]])
tensor([[3.1952]])
#406 Loss: 0.0032375396694988012
tensor([[1.1486],
        [1.7158]])
tensor([[3.1953]])
#407 Loss: 0.003237250493839383
tensor([[1.1485],
        [1.7164]])
tensor([[3.1954]])
#408 Loss: 0.0032369710970669985
tensor([[1.1484],
        [1.7170]])
tensor([[3.1954]])
#409 Loss: 0.0032366837840527296
tensor([[1.1483],
        [1.7177]])
tensor([[3.1955]])
#410 Loss: 0.0032364018261432648
tensor([[1.1482],
        [1.7183]])
tensor([[3.1956]])
#411 Loss: 0.003236126853

tensor([[1.1334],
        [1.8047]])
tensor([[3.1937]])
#553 Loss: 0.0031998995691537857
tensor([[1.1333],
        [1.8053]])
tensor([[3.1936]])
#554 Loss: 0.003199661849066615
tensor([[1.1332],
        [1.8059]])
tensor([[3.1936]])
#555 Loss: 0.0031994276214390993
tensor([[1.1331],
        [1.8065]])
tensor([[3.1935]])
#556 Loss: 0.0031991798896342516
tensor([[1.1330],
        [1.8071]])
tensor([[3.1934]])
#557 Loss: 0.00319894147105515
tensor([[1.1329],
        [1.8077]])
tensor([[3.1933]])
#558 Loss: 0.0031987049151211977
tensor([[1.1328],
        [1.8082]])
tensor([[3.1933]])
#559 Loss: 0.0031984581146389246
tensor([[1.1327],
        [1.8088]])
tensor([[3.1932]])
#560 Loss: 0.003198229940608144
tensor([[1.1325],
        [1.8094]])
tensor([[3.1931]])
#561 Loss: 0.0031979891937226057
tensor([[1.1324],
        [1.8100]])
tensor([[3.1930]])
#562 Loss: 0.003197751007974148
tensor([[1.1323],
        [1.8106]])
tensor([[3.1930]])
#563 Loss: 0.0031975109595805407
tensor([[1.1322],
        

        [1.8905]])
tensor([[3.1786]])
#703 Loss: 0.003165021538734436
tensor([[1.1170],
        [1.8910]])
tensor([[3.1785]])
#704 Loss: 0.0031647905707359314
tensor([[1.1169],
        [1.8916]])
tensor([[3.1784]])
#705 Loss: 0.0031645651906728745
tensor([[1.1168],
        [1.8922]])
tensor([[3.1782]])
#706 Loss: 0.0031643379479646683
tensor([[1.1167],
        [1.8927]])
tensor([[3.1781]])
#707 Loss: 0.0031641137320548296
tensor([[1.1166],
        [1.8933]])
tensor([[3.1780]])
#708 Loss: 0.0031638825312256813
tensor([[1.1165],
        [1.8938]])
tensor([[3.1779]])
#709 Loss: 0.003163660876452923
tensor([[1.1164],
        [1.8944]])
tensor([[3.1778]])
#710 Loss: 0.003163433400914073
tensor([[1.1163],
        [1.8950]])
tensor([[3.1776]])
#711 Loss: 0.003163206623867154
tensor([[1.1162],
        [1.8955]])
tensor([[3.1775]])
#712 Loss: 0.003162974491715431
tensor([[1.1161],
        [1.8961]])
tensor([[3.1774]])
#713 Loss: 0.0031627549324184656
tensor([[1.1160],
        [1.8966]])
tensor(

#848 Loss: 0.003132734214887023
tensor([[1.1023],
        [1.9714]])
tensor([[3.1598]])
#849 Loss: 0.003132519545033574
tensor([[1.1022],
        [1.9719]])
tensor([[3.1597]])
#850 Loss: 0.003132293000817299
tensor([[1.1021],
        [1.9725]])
tensor([[3.1595]])
#851 Loss: 0.003132081590592861
tensor([[1.1020],
        [1.9730]])
tensor([[3.1594]])
#852 Loss: 0.003131859702989459
tensor([[1.1019],
        [1.9736]])
tensor([[3.1593]])
#853 Loss: 0.0031316454987972975
tensor([[1.1018],
        [1.9741]])
tensor([[3.1591]])
#854 Loss: 0.003131423844024539
tensor([[1.1017],
        [1.9747]])
tensor([[3.1590]])
#855 Loss: 0.003131207777187228
tensor([[1.1016],
        [1.9752]])
tensor([[3.1589]])
#856 Loss: 0.003130990779027343
tensor([[1.1015],
        [1.9758]])
tensor([[3.1587]])
#857 Loss: 0.0031307667959481478
tensor([[1.1014],
        [1.9763]])
tensor([[3.1586]])
#858 Loss: 0.0031305502634495497
tensor([[1.1013],
        [1.9769]])
tensor([[3.1585]])
#859 Loss: 0.0031303318683058

tensor([[3.1408]])
#990 Loss: 0.00310224830172956
tensor([[1.0893],
        [2.0486]])
tensor([[3.1407]])
#991 Loss: 0.0031020333990454674
tensor([[1.0892],
        [2.0491]])
tensor([[3.1405]])
#992 Loss: 0.0031018268782645464
tensor([[1.0892],
        [2.0497]])
tensor([[3.1404]])
#993 Loss: 0.003101613139733672
tensor([[1.0891],
        [2.0502]])
tensor([[3.1402]])
#994 Loss: 0.0031014038249850273
tensor([[1.0890],
        [2.0507]])
tensor([[3.1401]])
#995 Loss: 0.00310119497589767
tensor([[1.0889],
        [2.0513]])
tensor([[3.1400]])
#996 Loss: 0.003100978909060359
tensor([[1.0888],
        [2.0518]])
tensor([[3.1398]])
#997 Loss: 0.0031007740180939436
tensor([[1.0887],
        [2.0524]])
tensor([[3.1397]])
#998 Loss: 0.003100562607869506
tensor([[1.0887],
        [2.0529]])
tensor([[3.1396]])
#999 Loss: 0.0031003477051854134
tensor([[1.0886],
        [2.0534]])
tensor([[3.1394]])
Predicted data based on trained weights: 
Input (scaled): 
tensor([0.5000, 1.0000])
Output: 
tenso

C:\tools\Anaconda3\lib\site-packages\torch\serialization.py:256: UserWarning: Couldn't retrieve source code for container of type Neural_Network. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
